name: Lint

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - main
      - develop

jobs:
  linter:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Node Version
        uses: actions/setup-node@v2
        with:
          node-version: 16.11.1
      - name: NPM cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn install
      - name: ESLint
        run: yarn lint
