name: Unit Tests

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - main
      - develop

jobs:
  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Node Version
        uses: actions/setup-node@v2
        with:
          node-version: 16.11.1
      - name: NPM cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn install
      - name: Unit tests with coverage
        run: yarn test:coverage
      - name: Upload reports to codecov
        uses: codecov/codecov-action@v2
        with:
          files: ./.coverage/clover.xml,./.coverage/coverage-final.json,./.coverage/lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
          name: codecov-ndx-ui-kit
          verbose: true
